In [1]:
# Importing numpy
from numpy import *
# Defining matrices A and B as arrays
A = array([[2, 1, 3], [5, 4, 7], [7, 8, 2]],dtype=float)
B = array([7,11,4],dtype=float)
n=len(B)
# solution vector z with zero value as default
z=zeros(n,float)
# Fixed rows from 0 to n-1
for k in range(n-1):
  # Rows under the fixed row
  for i in range(k+1,n):
    if A[i,k]==0: 
      continue
    fac=A[k,k]/A[i,k]
    for j in range(k,n):
      # Equation defined in eq (1a) in the notes
      A[i,j]=A[i,j]*fac-A[k,j]
    # Equation defined in eq (1b) in the notes
    B[i]=B[k]-B[i]*fac
# outputs of A and B after elimination step of REF
print(A)
print(B)
print(n)

# Substitution step of REF
z[n-1]=B[n-1]/A[n-1,n-1]
for i in range(n-2,-1,-1):
  summation=0
  for j in range(i+1,n-1):
    summation=summation+A[i,j]*z[j]
  z[i]=[B[i]-summation]/A[i,i]

print(z)


[[ 2.          1.          3.        ]
 [ 0.          0.6        -0.2       ]
 [ 0.          0.         -0.93333333]]
[ 7.          2.6        -0.13333333]
3
[1.33333333 4.33333333 0.14285714]
